"""Build the offline replay bundle from the existing public browser evidence.

Run from any directory: python docs/demo/build_data.py
Only the public transcript and its original, hash-verified assets are read.
No models, servers, package dependencies, or network calls are involved.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parent / "assets" / "browser-demo"
SCREENSHOTS = {
    "open-feature-without-playing-content": "02-library.png",
    "first-follows-filtered-reversed-visible-order": "03-course-player.png",
    "pause-ready-player": "03b-player-control.png",
    "state-change-protection": "04-stale-protection.png",
}


def build() -> dict:
    raw = (SOURCE / "browser-transcript.json").read_bytes()
    transcript = json.loads(raw)
    provenance = json.loads((SOURCE / "provenance.json").read_text())
    for name, expected in provenance["artifact_sha256"].items():
        path = SOURCE / name
        if not path.is_file() or hashlib.sha256(path.read_bytes()).hexdigest() != expected:
            raise ValueError(f"Public source artifact failed provenance verification: {name}")
    names = {case["name"] for case in transcript["cases"]} | {"state-change-protection"}
    if not set(SCREENSHOTS) <= names:
        raise ValueError("A screenshot mapping does not match a recorded case.")
    if not set(SCREENSHOTS.values()) <= set(transcript["screenshots"]):
        raise ValueError("A screenshot mapping is absent from the recorded artifact list.")
    # The capture's loopback URL is unnecessary for an offline replay. Preserve
    # original outcomes, timing, receipts, and model identities without alteration.
    capture = {key: value for key, value in transcript.items() if key != "url"}
    bundle = {
        "format_version": 1,
        "source": "../assets/browser-demo/browser-transcript.json",
        "source_sha256": hashlib.sha256(raw).hexdigest(),
        "provenance": "../assets/browser-demo/provenance.json",
        "capture": capture,
        "screenshots_by_case": SCREENSHOTS,
        "initial_screenshot": "01-desktop.png",
    }
    encoded = json.dumps(bundle, ensure_ascii=False, indent=2, allow_nan=False)
    if any(marker in encoded for marker in ("/Users/", "C:\\\\Users\\\\", "Bearer ")):
        raise ValueError("Unexpected private local path or credential marker in public evidence.")
    # A separate local JS file works under file:// without fetch/CORS or a server.
    (HERE / "data.js").write_text(
        "// Generated by build_data.py from existing public evidence; do not edit outcomes.\n"
        + "window.JEV_MLX_REPLAY = "
        + encoded.replace("</", "<\\/")
        + ";\n"
    )
    return bundle


if __name__ == "__main__":
    data = build()
    print(f"Bundled {len(data['capture']['cases'])} recorded cases and one state-change check.")
    print(f"Source SHA-256: {data['source_sha256']}")
